spring:
  application:
    name: alumni-portal
  datasource:
    password: pass
    url: jdbc:postgresql://localhost:5433/alumni-portal
    username: username
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8080

aws:
  zone: us-east-1
  s3:
    access_key: accessKey
    secret_key: secretKey

keycloak:
  realm: waa
  auth-server-url: http://localhost:8081
  resource: backend
  public-client: true
  bearer-only: true
